ci: fail properly when script fails or times out
We allow the check-docstrings CI to fail so we can save a partial cache,
but we do want to report that failure eventually. Add another step to
the job that fails appropriately.

diff --git a/.github/workflows/check_docstrings.yml b/.github/workflows/check_docstrings.yml
--- a/.github/workflows/check_docstrings.yml
+++ b/.github/workflows/check_docstrings.yml
@@ -91,3 +91,10 @@ jobs:
         with:
           path: ${{ env.CRYPTOL_CACHE }}
           key: ${{ env.CRYPTOL_CACHE_KEY }}
+
+      # After potentially uploading the cache, we fail according to the checkscript step.
+      - name: "Check whether the script failed"
+        if: steps.checkscript.outcome != 'success'
+        run: |
+          echo "Docstrings script failed with ${{ steps.checkscript.outcome }}"
+          exit 1
